Repository matter-labs/era-shivini, pull requests merged in 2023-12, with the labels that each got.

#16 Adapt to changes introduced by the CUDA execution refactoring in boojum-cuda
  src/primitives/arith.rs
Labels: refactoring

#18 improve allocator stats
  src/prover.rs
  src/static_allocator/device.rs
Labels: enhancement

#20 use PACKED_PLACEHOLDER_BITMASK constant instead of raw value
  src/prover.rs
  src/test.rs
Labels: refactoring

#21 implement set_by_value and fix set_value_generic comment
  src/primitives/helpers.rs
Labels: enhancement

#17 NTT housekeeping
  src/data_structures/arguments.rs
  src/data_structures/setup.rs
  src/data_structures/storage.rs
  src/data_structures/trace.rs
  src/oracle.rs
  src/poly.rs
  src/primitives/arith.rs
  src/primitives/ntt.rs
  src/prover.rs
Labels: enhancement, refactoring
